name: step variable practical
on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: show application name
        env:
          APP_NAME: my-app
          NODE_ENV: production
        run: |
          echo "Application name is $APP_NAME"
          echo "Node environment is $NODE_ENV"
        
      - name: show node environment
        run: |
          echo "Application name is $APP_NAME"
          echo "Node environment is $NODE_ENV"
          
